### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by smcavallo**
* Added dockerfile

To Build ->  `docker build --tag nr-grafana-migration:local .`
To Run -> `docker run --rm -it nr-grafana-migration:local`

* misc format fixes

* Updated all packages

```

pip install pip-upgrader
pip-upgrade --skip-package-installation

Available upgrades:
+------+-------------------------+-----------------+----------------+---------------------+
| No.  | Package                 | Current version | Latest version | Release date        |
+------+-------------------------+-----------------+----------------+---------------------+
|  1   |  aiohttp                | 3.7.4.post0     | 4.0.0a1        | 2019-10-09 11:29:30 |
|  2   |  astroid                | 2.4.2           | 2.12.12        | 2022-10-19 08:48:48 |
|  3   |  async-timeout          | 3.0.1           | 4.0.2          | 2021-12-20 09:14:53 |
|  4   |  attrs                  | 20.3.0          | 22.1.0         | 2022-07-28 13:20:27 |
|  5   |  browser-cookie3        | 0.12.0          | 0.16.2         | 2022-10-04 18:09:38 |
|  6   |  certifi                | 2020.12.5       | 2022.9.24      | 2022-09-24 14:26:51 |
|  7   |  cffi                   | 1.14.5          | 1.15.1         | 2022-06-30 18:15:07 |
|  8   |  chardet                | 4.0.0           | 5.0.0          | 2022-06-25 04:27:55 |
|  9   |  cryptography           | 3.4.6           | 38.0.3         | 2022-11-01 21:47:28 |
|  10  |  idna                   | 2.10            | 3.4            | 2022-09-14 00:24:23 |
|  11  |  importlib-metadata     | 3.7.3           | 5.0.0          | 2022-10-02 00:42:11 |
|  12  |  isort                  | 5.6.4           | 5.10.1         | 2021-11-09 05:42:44 |
|  13  |  jeepney                | 0.6.0           | 0.8.0          | 2022-04-03 17:58:16 |
|  14  |  keyring                | 23.0.0          | 23.11.0        | 2022-11-05 13:43:25 |
|  15  |  lazy-object-proxy      | 1.4.3           | 1.8.0          | 2022-10-26 13:38:00 |
|  16  |  lz4                    | 3.1.3           | 4.0.2          | 2022-07-24 11:51:16 |
|  17  |  mccabe                 | 0.6.1           | 0.7.0          | 2022-01-24 01:14:49 |
|  18  |  multidict              | 5.1.0           | 6.0.2          | 2022-01-24 16:56:02 |
|  19  |  prompt-toolkit         | 3.0.18          | 3.0.32         | 2022-11-03 16:32:36 |
|  20  |  pycparser              | 2.20            | 2.21           | 2021-11-06 12:50:13 |
|  21  |  pycryptodome           | 3.10.1          | 3.15.0         | 2022-06-22 20:49:09 |
|  22  |  pylint                 | 2.6.0           | 2.15.5         | 2022-10-21 21:19:28 |
|  23  |  python-graphql-client  | 0.4.2           | 0.4.3          | 2021-03-04 21:32:03 |
|  24  |  questionary            | 1.9.0           | 1.10.0         | 2021-07-15 10:11:00 |
|  25  |  requests               | 2.25.1          | 2.28.1         | 2022-06-29 15:13:40 |
|  26  |  SecretStorage          | 3.3.1           | 3.3.3          | 2022-08-13 16:22:44 |
|  27  |  selenium               | 3.141.0         | 4.6.0          | 2022-11-04 10:36:27 |
|  28  |  six                    | 1.15.0          | 1.16.0         | 2021-05-05 14:18:17 |
|  29  |  typing-extensions      | 3.7.4.3         | 4.4.0          | 2022-10-06 22:40:00 |
|  30  |  urllib3                | 1.26.2          | 1.26.12        | 2022-08-22 13:27:19 |
|  31  |  websockets             | 8.1             | 10.4           | 2022-10-25 20:10:29 |
|  32  |  wrapt                  | 1.12.1          | 1.14.1         | 2022-05-02 05:26:13 |
|  33  |  yarl                   | 1.6.3           | 1.8.1          | 2022-08-02 07:12:14 |
|  34  |  zipp                   | 3.4.1           | 3.10.0         | 2022-10-24 01:21:48 |
+------+-------------------------+-----------------+----------------+---------------------+
```

### CODE REVIEW

**Comment by kidk** [comment]
Thanks @smcavallo 

There's seem to be a lot of linting improvements in this PR. How did you lint your files? 

I'd remove those changes from these PR and add them to another one if possible.

**Comment by smcavallo** [comment]
hi @kidk - I have reverted the formatting fixes.  It's ready for review.

**Review by kidk — APPROVED** [review]

**Comment by kidk** [comment]
@smcavallo Thanks a lot, merged

Out of interest what did you use for the auto formatting?

**Comment by smcavallo** [comment]
@kidk - I just used the built-in python linting and formatting built into [Pycharm](https://www.jetbrains.com/pycharm/)
it would probably be good to wire up something like this into a github action PR pipeline ->  https://github.com/marketplace/actions/python-code-quality-and-lint

**Pull request merged**
